{{- if .Values.app.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $i, $secret := .Values.app.secrets }}
  {{ $secret.name }}: {{ $secret.value | b64enc }}
{{- end }}
{{- if .Values.app.secretsType }}
type:
  {{ .Values.app.secretsType }}
{{- end }}
{{- end -}}